name: Manual

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment'
        type: environment
        required: true

run-name: Deploy to environment '${{ inputs.target_env }}'

jobs:
  trigger-test:
    name: Deployment to '${{ inputs.target_env }}'
    concurrency: 
      group: ${{ inputs.target_env }}
      cancel-in-progress: true
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}
      test_value: 'manual'

  second-approve:
    name: Second approval bound job using '${{ inputs.target_env }}'
    concurrency: 
      group: ${{ inputs.target_env }}
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}
      test_value: 'second approval'

  second-job:
    concurrency: 
      group: ${{ inputs.target_env }}
    runs-on: ubuntu-latest
    steps:
      - name: Print somehting after approve
        run: echo Something after approve...
