name: Test

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment'
        type: environment
        required: true
      test_value:
        description: 'Test value'
        type: string
        required: true

run-name: Test using ${{ inputs.target_env }}

jobs:
  test-values:
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.target_env }}
    environment: ${{ inputs.target_env }}

    steps:
      - name: Test workflow
        run: |
          echo "plain_value: ${{ inputs.test_value }}"
          echo "actor: ${{ github.actor }}"
          echo "triggering actor: ${{ github.triggering_actor }}"
          echo "env var: ${{ vars.DB_HOST }}"
          echo "env secret: ${{ secrets.DB_CREDENTIALS }}"
          echo Approve at: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
