name: Test

on:
  workflow_call:
    inputs:
      target_env:
        description: 'Target environment'
        type: string
        required: true
      execution_mode:
        description: 'Execution mode'
        type: string
        required: true

run-name: 'DB migrations: ${{ inputs.target_env }} / ${{ inputs.execution_mode }}'

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Checkout PR
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment
        run: |
          echo LIQUIBASE_SHOW_BANNER="false" > .liquibase.env
          echo LIQUIBASE_COMMAND_USERNAME="${{ secrets.LIQUIBASE_COMMAND_USERNAME }}" >> .liquibase.env
          echo LIQUIBASE_COMMAND_PASSWORD="${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}" >> .liquibase.env
          echo LIQUIBASE_COMMAND_URL="${{ vars.LIQUIBASE_COMMAND_URL }}" >> .liquibase.env

      - name: Run migrations
        run: |
          scripts/run-db-migrations.sh ${{ inputs.execution_mode }}

      - name: Comment migration diff
        if: "${{ inputs.execution_mode == 'plan' && inputs.target_env == 'database-dev' }}"
        run: |
          echo "## DB migration diff (${{ inputs.target_env }})" > body
          echo "\`\`\`sql" >> body
          cat liquibase/lb-diff.sql >> body
          echo "\`\`\`" >> body
          gh pr comment ${{ github.event.issue.number }} --body-file body
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
