name: Test

on:
  workflow_call:
    inputs:
      target_env:
        description: 'Target environment'
        type: string
        required: true
      execution_mode:
        description: 'Execution mode'
        type: string
        required: true

run-name: 'DB migrations: ${{ inputs.target_env }} / ${{ inputs.execution_mode }}'

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Test workflow
        run: |
          echo Approve at: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Execution mode: ${{ inputs.execution_mode }}"
          echo "actor: ${{ github.actor }}"
          echo "triggering actor: ${{ github.triggering_actor }}"
          echo "env var: ${{ vars.DEV_TEST_ENV_VAR }}"
  
          # dump github event context
          echo "${{ toJson(github.event) }}"
